version: '3.3'
services:
    server:
      platform: linux/arm64/v8
      build:
        context: ./
        dockerfile: ./server/Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DEBUG: 'True'
        DATABASE_URL: 'postgres://deals_admin:123456@db:5432/deals'

    db:
      platform: linux/arm64/v8
      image: postgres:14.6-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/
      environment:
        POSTGRES_DB: deals
        POSTGRES_USER: deals_admin
        POSTGRES_PASSWORD: 123456

volumes:
  postgres_data:
