version: '3.3'

services:
    nginx:
      build:
        context: ./
        dockerfile: ./nginx/Dockerfile
      depends_on:
        - server
      ports:
        - 80:80
      volumes:
        - ./server/media:/nginx/media

    server:
      restart: always
      build:
        context: ./
        dockerfile: ./server/Dockerfile.prod
      command: gunicorn config.wsgi -c ./config/gunicorn.py
      volumes:
        - ./server/media:/server/media
      depends_on:
        - db
      environment:
        DEBUG: 'False'
        DATABASE_URL: 'postgres://deals_admin:123456@db:5432/deals'

    db:
      restart: always
      platform: linux/arm64/v8
      image: postgres:14.6-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/
      environment:
        POSTGRES_DB: deals
        POSTGRES_USER: deals_admin
        POSTGRES_PASSWORD: 123456


volumes:
  postgres_data:
