# Generated by Django 3.2.2 on 2023-05-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин пользователя')),
                ('total', models.IntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Колличество товара')),
                ('date', models.DateTimeField(verbose_name='Дата сделки')),
                ('gems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='analytics.gem', verbose_name='Камень')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-date'],
            },
        ),
    ]
