# Generated by Django 3.2.2 on 2023-05-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, verbose_name='Логин пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название камня')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Колличество товара')),
                ('date', models.DateTimeField(verbose_name='Колличество товара')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='analytics.customer', verbose_name='Покупатель')),
                ('gems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='analytics.gems', verbose_name='Камень')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['-date'],
            },
        ),
    ]
